version: '3.1'

services:
  server:
    image: ubuntu:latest
    volumes:
      - "./server:/usr/local/src"
    entrypoint: /usr/local/src/scripts/entrypoint
    links:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fuckcoin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
