# serverless.yml

service: serverless-flask

plugins:
  - serverless-dynamodb-local
  - serverless-python-requirements
  - serverless-wsgi

custom:
  wsgi:
    app: src.app.app
    packRequirements: false
    pythonBin: python3
  pythonRequirements:
    dockerizePip: non-linux
  dynamodb:
      start:
        migrate: true

provider:
  name: aws
  runtime: python3.6
  stage: ${opt:stage}
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["TransactionsDynamoDBTableDev", "Arn" ] }
        - { "Fn::GetAtt": ["TransactionsDynamoDBTableProd", "Arn" ] }
  environment:
    TRANSACTIONS_TABLE: "transactions-table-${opt:stage}"

functions:
  app:
    handler: wsgi.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

resources:
  Resources:
    TransactionsDynamoDBTableDev:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: fuckcoinId
            AttributeType: S
          -
            AttributeName: when
            AttributeType: S
        KeySchema:
          -
            AttributeName: fuckcoinId
            KeyType: HASH
          -
            AttributeName: when
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'transactions-table-dev'
    TransactionsDynamoDBTableProd:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: fuckcoinId
            AttributeType: S
          -
            AttributeName: when
            AttributeType: S
        KeySchema:
          -
            AttributeName: fuckcoinId
            KeyType: HASH
          -
            AttributeName: when
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'transactions-table-prod'
