"""empty message

Revision ID: 1301d1a39ce3
Revises: 
Create Date: 2018-07-16 03:43:55.857758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1301d1a39ce3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fuckcoin_id', sa.Integer(), nullable=False),
    sa.Column('giver', sa.Unicode(length=255), nullable=False),
    sa.Column('recipient', sa.Unicode(length=255), nullable=False),
    sa.Column('when', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###
