"""empty message

Revision ID: 19411d69a7df
Revises: 1301d1a39ce3
Create Date: 2018-07-16 05:15:02.218540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19411d69a7df'
down_revision = '1301d1a39ce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('purpose', sa.UnicodeText(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'purpose')
    # ### end Alembic commands ###
